service: volunteer-chat-bot

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs4.3
  stage: bjdev
  profile: showcase

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
