service: volunteer-chat-bot

plugins:
  - serverless-webpack
  - serverless-mocha-plugin
  - serverless-plugin-write-env-vars
  - serverless-dynamodb-local

custom:
  webpackIncludeModules: true
  defaultStage: staging
  defaultAccount: '333126681707'
  envVars: ${file(./env_vars.yml)}
  writeEnvVars:
    NODE_ENV: ${opt:stage, self:custom.defaultStage}
    PAGE_ACCESS_TOKEN: ${self:custom.envVars.${opt:stage,self:custom.defaultStage}_page_access_token}
    VALIDATION_TOKEN: ${self:custom.envVars.${opt:stage,self:custom.defaultStage}_validation_token}
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migration: true

provider:
  name: aws
  runtime: nodejs4.3
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${opt:stage, self:custom.defaultStage}
  iamRoleARN: arn:aws:iam::${opt:account, self:custom.defaultAccount}:role/lambda_full_access

functions:
  challenge:
    handler: bot.challenge
    events:
      - http:
          method: get
          path: webhook
          integration: lambda
    memorySize: 512
  chat:
    handler: bot.chat
    events:
      - http:
          method: post
          path: webhook
          integration: lambda
    memorySize: 512
    timeout: 300
  message:
    handler: bot.message
    memorySize: 512
    timeout: 300

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: volunteer-chat-bot-${opt:stage, self:custom.defaultStage}-members
        AttributeDefinitions:
          - AttributeName: fbid
            AttributeType: S
        KeySchema:
          - AttributeName: fbid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
