service: volunteer-chat-bot

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs4.3
  stage: bjdev
  profile: showcase

functions:
  challenge:
    handler: bot.challenge
    events:
      - http:
          method: get
          path: webhook
  chat:
    handler: bot.chat
    events:
      - http:
          method: post
          path: webhook
