service: volunteer-chat-bot

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-mocha-plugin

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs4.3
  stage: staging
  profile: showcase

functions:
  challenge:
    handler: bot.challenge
    events:
      - http:
          method: get
          path: webhook
    memorySize: 512
  chat:
    handler: bot.chat
    events:
      - http:
          method: post
          path: webhook
    memorySize: 512
    timeout: 300
